apiVersion: 1

datasources:
  - name: InfluxDB-Beeorn
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: beeorn-org
      defaultBucket: hive-data
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true
